### PR TITLE
Fix travis-ci

### PR DESCRIPTION
**Pull request by op01**
# 30

### CODE REVIEW

**Comment by kasunkv** [comment]
Closing and reopening to trigger travis-ci build

**Comment by kosalanuwan** [comment]
@op01 Build error says node and jasmine not found. Probably due to types array in tsconfig.json.

**Comment by kasunkv** [comment]
Closing and opening to re-trigger travis build

**Comment by charithsoori** [comment]
Enabled build on pull requests ,too

**Comment by kasunkv** [comment]
Disabling manual trigger of protractor test run fixed the build. Travis automatically started the npm run test and it contained the command to run the  protractor tests. 3rd test failed due to an issue with the site that the tests was running against. A new dummy site will be created for this. Task is open in issues. #2

**Pull request merged**
